# Generated by Django 3.2.8 on 2024-08-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingSettings',
        ),
    ]
