# Generated by Django 3.2.8 on 2024-09-16 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopManagement', '0004_alter_shopprofile_phone_number'),
        ('bookingManagement', '0002_delete_bookingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBookingsCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_bookings', models.IntegerField(default=0, help_text='number of bookings for that barber in that date and time')),
                ('booking_date', models.DateField(null=True)),
                ('booking_time', models.TimeField(null=True)),
                ('shop_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopManagement.shopprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='BarberBookings',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopManagement.shopservice'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='shop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopManagement.shopprofile'),
        ),
    ]
