# Generated by Django 3.2.8 on 2024-09-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopManagement', '0004_alter_shopprofile_phone_number'),
        ('bookingManagement', '0003_auto_20240916_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='shop_id',
            new_name='shop_profile',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='service_id',
            new_name='shop_service',
        ),
        migrations.RenameField(
            model_name='shopbookingscounter',
            old_name='shop_id',
            new_name='shop_profile',
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingManagement.booking')),
                ('shop_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopManagement.shopservice')),
            ],
        ),
    ]
