# Generated by Django 3.2.8 on 2024-08-25 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('shop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shop_name', models.CharField(max_length=255)),
                ('about_us', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.DurationField(help_text='Duration of the service (e.g., 00:30:00 for 30 minutes)')),
                ('shop_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_name', to='shopManagement.shopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_enable', models.BooleanField(default=True)),
                ('confirmation_required', models.BooleanField(default=True)),
                ('disable_weekend', models.BooleanField(default=True)),
                ('available_booking_months', models.IntegerField(default=1, help_text='if 2, user can only book booking for next two months.')),
                ('max_booking_per_day', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period_of_each_booking', models.CharField(choices=[('5', '5M'), ('10', '10M'), ('15', '15M'), ('20', '20M'), ('25', '25M'), ('30', '30M'), ('35', '35M'), ('40', '40M'), ('45', '45M'), ('60', '1H'), ('75', '1H 15M'), ('90', '1H 30M'), ('105', '1H 45M'), ('120', '2H'), ('150', '2H 30M'), ('180', '3H')], default='30', help_text='How long each booking take.', max_length=3)),
                ('max_booking_per_time', models.IntegerField(default=1, help_text='how much booking can be book for each time.')),
                ('shop_profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shop_preferences', to='shopManagement.shopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShopServicesImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='service_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_service_images', to='shopManagement.shopservice')),
            ],
        ),
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('review_body', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('shop_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shopManagement.shopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShopProfileImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='shop_images/')),
                ('shop_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopManagement.shopprofile')),
            ],
        ),
    ]
