# Generated by Django 3.2.8 on 2024-09-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
