# Generated by Django 3.2.8 on 2024-09-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopManagement', '0003_auto_20240914_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
