# Generated by Django 3.2.8 on 2024-09-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopManagement', '0004_alter_shopprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
