# Generated by Django 3.2.8 on 2024-09-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopManagement', '0006_barberdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='venue_amenities',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
